### ISSUE TITLE
tree module in python can't be installed

### ISSUE THREAD

**Issue by Rojo14** [dauparas/LigandMPNN#17]
Hi, 

I can't import the "tree" module in python3.11 even if I can find the module in my conda environment. I have a Mac. Is it an issue that occurred to someone else? Thanks

**Comment by tstja015** [comment]
"pip install dm-tree" did the trick for me.

**Comment by Rojo14** [comment]
Thanks! 
I tried it but I still have the same issue

**Comment by emilyrkang** [comment]
I'm also having this issue. I tried "pip install tree" "pip install dm-tree" and each of those with "pip3" and "pip3.10". I think it's an issue with the openfold install? I am running Windows 11 Pro and[ OpenFold](https://github.com/aqlaboratory/openfold) only has instructions for a linux install. Can LigandMPNN run on Windows?

**Comment by YaoYinYing** [comment]
> Can LigandMPNN run on Windows?

As far as I tested, LigandMPNN can perfectly work w/o sidechain modeling on Windows. See here: https://github.com/dauparas/LigandMPNN/pull/16

**Comment by dauparas** [comment]
Now there is also a requirements.txt file available:

`conda create -n ligandmpnn_env python=3.11
pip3 install -r requirements.txt`
