### ISSUE TITLE
Segmentation fault when winning on MAC oc

### ISSUE THREAD

**Issue by Vepricov** [dauparas/LigandMPNN#19]
Hello, I am facing an error: python gives segmentation fault when it tries to execute `model.load_state_dict(checkpoint["model_state_dict"])` command in line 90 of `run.py` file. 

When I commented it out, I was getting these kinds of errors again in the `ProteinFeaturesLigand()` class.

Help me to solve the problem, please 🥺🙏

**Comment by dauparas** [comment]
Try setting up a conda environment using requirements.txt file, I hope this helps!
