### ISSUE TITLE
Timeout for wget model parameters

### ISSUE THREAD

**Issue by merttopcu-rhea** [dauparas/LigandMPNN#22]
I'm getting timed out when trying to get model parameters. 
Is this a known issue or is there anything I need to do?

Thanks.

**Comment by ISDementyev** [comment]
I am getting something similar, both when I try to run with the bash file (`-q` disabled) and when I try to run the commands directly on the terminal.
Trying to access the links using the web doesn't work either.
I am assuming this is only a temporary issue which will be fixed soon, but I am not certain.

**Comment by agarrubio** [comment]
I must add that, when wget fails, chrome has no problem downloading the files.
