### ISSUE TITLE
Typo in README.md file and argparser help text for example of fixing/redesigning/parsing specific chains

### ISSUE THREAD

**Issue by amelie-iska** [dauparas/LigandMPNN#25]
For example, in the following CLI command examples in `README.md`:

**17 --chains_to_design**
*Specify which chains (e.g. "ABC") need to be redesigned, other chains will be kept fixed. Outputs in seqs/backbones will still have atoms/sequences for the whole input PDB.*

**18 --parse_these_chains_only**
*Parse and design only specified chains (e.g. "ABC"). Outputs will have only specified chains.*

multiple chains should be comma separated, that is "A,B,C" instead of "ABC", as per the parsing code (see lines 272-273 in `run.py` for example):

```python
if type(args.chains_to_design) == str:
            chains_to_design_list = args.chains_to_design.split(",")
```

Additionally, the help text for argparser flags (see lines 883-888 in `run.py` for example):
```python
argparser.add_argument(
        "--parse_these_chains_only",
        type=str,
        default="",
        help="Provide chains letters for parsing backbones, 'ABCF'",
    )
```
should also have multiple chains separated by commas.

**Comment by dauparas** [comment]
Thank you for spotting this! Fixed now: https://github.com/dauparas/LigandMPNN/commit/84614f993220a5a1243c7c6b2360d886c62781f8
