### ISSUE TITLE
Multiple sequence design for one target

### ISSUE THREAD

**Issue by lzygitk7** [dauparas/LigandMPNN#26]
Does LigandMPNN have the same argument as ProteinMPNN?
```
argparser.add_argument("--num_seq_per_target", type=int, default=1, help="Number of sequences to generate per target")
```
The side chain argument: `--number_of_packs_per_design` does not seem to affect the protein sequence level.
Or LigandMPNN can only generate one sequence per target?

**Comment by ShuhaoGithub** [comment]
(Not author) It's replaced by number of batches and batch size.

**Comment by lzygitk7** [comment]
> (Not author) It's replaced by number of batches and batch size.

Got it. Thank you very much.
